name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create hook for readchar
      run: |
        echo "from PyInstaller.utils.hooks import copy_metadata" > hook-readchar.py
        echo "datas = copy_metadata('readchar')" >> hook-readchar.py

    - name: Build executable
      run: |
        pyinstaller --onefile --additional-hooks-dir=. serial_to_csv.py
    - name: Check if executable exists
      run: ls -l dist/

    - name: Upload Windows executable to GitHub Release
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: dist/serial_to_csv.exe

    - name: Upload Mac executable to GitHub Release
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v3
      with:
        name: macos-executable
        path: dist/serial_to_csv

    - name: Upload Linux executable to GitHub Release
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: linux-executable
        path: dist/serial_to_csv


  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create a tag for this commit
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        git tag $TAG_NAME
        git push origin $TAG_NAME
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

    - name: Create a Release
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: "Logger"
        body: "Compiled executables"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Download Windows executable artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-executable
        path: windows

    - name: Download Mac executable artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-executable
        path: macos

    - name: Download Linux executable artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-executable
        path: linux

    - name: List the directory
      run: ls -R .


    - name: Upload Linux executable to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./linux/serial_to_csv  # Path to the Linux executable
        asset_name: serial_to_csv-linux  # Name of the asset
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows executable to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./windows/serial_to_csv.exe  # Path to the Windows executable
        asset_name: serial_to_csv-windows.exe  # Name of the asset
        asset_content_type: application/octet-stream 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Upload macOS executable to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./macos/serial_to_csv  # Path to the macOS executable
        asset_name: serial_to_csv-macos  # Name of the asset
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
