name: Build Executables

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Replace with your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Create hook for readchar
      run: |
        echo "from PyInstaller.utils.hooks import copy_metadata" > hook-readchar.py
        echo "datas = copy_metadata('readchar')" >> hook-readchar.py

    - name: Build executable
      run: |
        pyinstaller --onefile --additional-hooks-dir=. serial_to_csv.py

    - name: Create a tag for this commit
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create a Release
      uses: softprops/action-gh-release@v1
      id: create_release
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          dist/serial_to_csv  # Linux
          dist/serial_to_csv.exe  # Windows
          dist/serial_to_csv.app  # macOS
